---
apiVersion: v1
kind: ConfigMap
metadata:
  name: ds-test
  annotations:
    grafana.net/datasource: "true"
    grafana.net/id: "0"
data:
  test.json: |-
    {
      "name": "Prometheus",
      "type": "prometheus",
      "access": "proxy",
      "url": "http://prometheus:9090",
      "basicAuth": false,
      "jsonData": {
        "httpMethod": "GET",
        "keepCookies": [],
        "queryTimeout": "60s",
        "timeInterval": "15s"
      },
      "isDefault": true
    }