kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "grafana.fullname" . }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ template "grafana.fullname" . }}
subjects:
- kind: ServiceAccount
  name: grafana
  namespace: {{ default .Release.Namespace .Values.global.namespace | quote }}
