{{- if .Values.ingress.enabled -}}
apiVersion: extensions/v1beta1
kind: Ingress
metadata:
  name: {{ template "grafana.name" . }}
  namespace: {{ default .Release.Namespace .Values.global.namespace | quote }}
  annotations:
    kubernetes.io/ingress.class: "nginx"
    ingress.kubernetes.io/force-ssl-redirect: "false"
    ingress.kubernetes.io/ssl-redirect: "false"
{{ if .Values.ingress.extraAnnotations -}}
{{ toYaml .Values.ingress.extraAnnotations | indent 4 }}
{{- end }}
spec:
  rules:
    - host: {{ .Values.ingress.url }}
      http:
        paths:
          - path: /
            backend:
              serviceName: {{ template "grafana.name" . }}
              servicePort: {{ .Values.service.port }}
{{- end }}
