kind: ClusterRole
apiVersion: rbac.authorization.k8s.io/v1beta1
metadata:
  name: {{ template "grafana.fullname" . }}
rules:
  - apiGroups: [""]
    resources:
      - configmaps
    verbs: ["get", "watch", "list"]
